### ISSUE TITLE
Separate tagging for "things we would be/do/have together"

### ISSUE THREAD

**Issue by BarefootSelkie** [AndreaUnlimited/starfriends#10]
Unless someone puts they are something the matching doesn't match with looking for. So it's quite conter intitutive what you need to put in your tags. e.g. If you're looking for friends, you won't find people unless they've said they are friends. 

Probably one to be folded back into nearing up the tag groups.

**Comment by fallax** [comment]
Yep, "I am friends" definitely sounds wrong - I think this is a similar problem to the "I am/I have" thing.

**Comment by Cassolotl** [comment]
My suggestion was three questions: I am/do/have, You are/do/have, and We'd be/do/have.

**Comment by fallerOfFalls** [comment]
heh, @Cassolotl I was just about to mention that. I think this is totally the solution.

**Comment by fallerOfFalls** [comment]
ugh that's terrible words. sorry.

**Comment by BarefootSelkie** [comment]
+1 for the I, You, We suggestion.

Also: Thanks, fallerOfFalls, learning difficulties mean language and wording aren't my best skills. I was trying to figure out a better way of wording it but couldn't it's helpful. 🙂

**Comment by fallax** [comment]
In general when I'm trying to explain to people how to write good online dating profiles, I tend to suggest writing something along the lines of "this is who I am, this is who I am looking for, this is what I'd do with you" - I think supporting this would be important for having good profiles.

People (especially most autistic people I know) who look at a blank unstructured text box and don't really know how to write a helpful profile description on an online dating site - providing this structure would be really helpful I think.

**Comment by fallerOfFalls** [comment]
This has been implemented now.
