### ISSUE TITLE
suggestion: separate REQUIRED and PREFERRED 'looking for' tag fields

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#11]
tags placed in the REQUIRED field exclude anyone who doesn't identify with that tag (so they don't appear in the list of matches on your home page). If you prefix with the NOT operator then excludes anyone who _does_ identify with that tag.

tags placed in the PREFERRED field affect match score... uh, somehow.

**Comment by Cassolotl** [comment]
+1!

**Comment by fallax** [comment]
This might help to resolve the problem in issue 9 https://github.com/AndreaUnlimited/starfriends/issues/9 I think - would allow making some things not important for match score?

**Comment by fallerOfFalls** [comment]
I don't think this resolves #9. we'll still need those operators. Although maybe REQUIRED and PREFERRED should also be operators?

PREFERRED could be the default.

Suffix a tag with `!` to make it REQUIRED.
So e.g. `-man!` will exclude anyone tags themselves as `man`.

I think I like this idea better than having separate fields. And I can't see any downsides.
