### ISSUE TITLE
Wanted: method for regular donations outside of Patreon

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#112]
A member has expressed a wish to donate a small amount monthly like you can with [Patreon](https://www.patreon.com/starfriends), but using PayPal instead.

You can initiate one-off payments using the email address andrea.parlafenetre@gmail.com, but on PayPal a standing-order type of arrangement must be set up by the payee. So Andréa is going to work on making a link or button on Starfriends (probably on the [About](https://www.starfriends.org/about) page) that you can click and choose your amount, and choose whether it's a monthly payment or a one-off payment.

**Comment by AndreaUnlimited** [comment]
I added a link to Paypal that allows for recurring donations!

**Comment by Cassolotl** [comment]
Nice one! :)
