### ISSUE TITLE
Wanted: "To: [people]" on new photo feed posts

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#115]
![screen shot 2017-02-14 at 13 30 03](https://cloud.githubusercontent.com/assets/6607512/22930770/d4d036c6-f2b9-11e6-8f9a-ecef04e29852.png)

It would be really cool if it showed on the new photo feed posts who would be able to see those posts. "To: everyone", etc.

**Comment by AndreaUnlimited** [comment]
If your settings allow it, public and profile pictures will be shared to your whitelist, private pictures will be shared to whoever is allowed to see said picture.
The message on feed says if the picture is a public picture, a profile picture or a private picture, so it's easy to find out!

**Comment by Cassolotl** [comment]
Awwwww noooo okay then. :D My brain is getting into the habit of looking for the little tag that says "to: whoever" so i find myself looking for it on picture posts too, but I get that it's probably not a big thing for anyone else!
