### ISSUE TITLE
Wanted: a way to "unlike" a thing

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#123]
Multi-like is great, but I can't unlike something. Plus my gut says to click the thumb again to unlike, which would have the opposite effect! But I don't want multi-like to go away.

**Comment by AndreaUnlimited** [comment]
Unless I limit the number of like per person (at least for feed posts or blog posts), that won't happen!

**Comment by Cassolotl** [comment]
Okay, I will tag and close accordingly. :)
