### ISSUE TITLE
Inconsistent spacing in matches page navigation

### ISSUE THREAD

**Issue by MyAlternateAccount** [AndreaUnlimited/starfriends#128]
I'm being a little pedantic here, and this is really really low priority, but here it is anyway:

The page switcher for matches has inconsistent spacing between the currently selected page (a `<b>` element) and links to other pages:

![1487742410](https://cloud.githubusercontent.com/assets/25602160/23198917/5543fb22-f890-11e6-8357-b1b81facb78d.png)

This is because the page switching links have 5px padding and the `<b>` containing the currently selected page doesn't.

This might occur in other places but I looked around a bit and didn't see anything obvious (feed uses a different sort of page navigation).

**Comment by AndreaUnlimited** [comment]
The page switcher has been updated where needed be, including the one at the bottom of the Matches page, with the all Semantic UI Revamp Extravaganza!
