### ISSUE TITLE
Welcome inbox message display/links corrupted

### ISSUE THREAD

**Issue by leahneukirchen** [AndreaUnlimited/starfriends#133]
It says:

> If you want to know more about what's in store in the next few months of development, head to the'  target='_blank' class='feed-auto-link' rel='nofollow'>https://starfriends.org/blog'>the dev blog! You can also join the' target='_blank' class='feed-auto-link' rel='nofollow'>https://telegram.me/starfriendsalpha'>the Telegram group used for staying in touch with the early users, or even help me track issues on' target='_blank' class='feed-auto-link' rel='nofollow'>https://github.com/AndreaUnlimited/starfriends/issues/'>on GitHub

and all links don't work.

**Comment by Cassolotl** [comment]
We thought we had fixed it! We're looking into it. Thanks!

**Comment by AndreaUnlimited** [comment]
It should be fixed now, and all previous messages with that problem should be corrected!
Thanks for your help!
