### ISSUE TITLE
Make sign up less intimidating

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#14]
Initial sign up process could do with some additional explanation to make it clear what the site is for and how to create a profile.

On initially opening the site, there isn't really much to explain what it is, why it'd be interesting to anyone, and why you'd sign up.

For people accessing the page for the first time, it is probably worth making the "create an account" features really obvious on the front page - see how Facebook does this:

![facebookinitialsignup](https://cloud.githubusercontent.com/assets/2036067/13372951/8d043492-dd51-11e5-9c3d-4169e300e965.png)

At the moment you have to look carefully at the page to find "Create an account" and it's the very last thing on the page.

Once you are trying to create an account, it's not clear what sort of things might be a good idea to put into the text boxes for "I am" and "I am looking for". We could probably do with some text underneath these saying things like "e.g. woman, nonbinary, disabled, kinky..." to indicate the sort of thing to put in here.

**Comment by Cassolotl** [comment]
The homepage when you're signed out now has the sign-up box at the top, with lots of text with headings underneath like "what is starfriends?" and "who can join starfriends?" etc. So it's a lot less scary. And there's some things on the "add your tags" page that make it less intimidating and confusing, like a link to the All Tags page.

So, this is good enough for now - I'll mark it closed, and if people have issues with the welcome/sign-up pages at any point they should open new issues here with specific problems outlined and such. :)
