### ISSUE TITLE
Clickable avatars in the feed

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#148]
Currently, usernames on the Feed tab are clickable, but avatars aren't. Clickable avatars are easier (more accessible, probably?) for opening people's profiles because they're a bigger target, so it's better especially on touchscreen devices too.

**Comment by AndreaUnlimited** [comment]
It doesn't show the little tooltip but otherwise it's done, not sure if that's enough to close so I'll leave it in your hands!

**Comment by Cassolotl** [comment]
It's good enough for me! :) It has the little pointy finger cursor so it's pretty obvious what it does, I think!

Thanks! 🎉
