### ISSUE TITLE
Impossible to open new messages in inbox

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#152]
[Anonymous message on Tumblr](http://strfrnds.tumblr.com/post/183921775677/hi-how-can-we-see-our-messages-it-says-that-i):

>hi how can we see our messages? it says that I have 1 from andrea (Unread Message - Click to open thread) in my inbox but there's nowhere to click besides her profile picture and it only takes me to her profile.

**Comment by AndreaUnlimited** [comment]
Thank you for noticing and taking the time to submitting the issue!
It is now fixed. Or rather, I added another layer to the link to prevent browser's differences to come in the way of its proper functioning: I am now using <a> around the div but also an onclick event that opens the target link on the div itself.
Thank you again and have a wonderful day!
