### ISSUE TITLE
Suggestion: Improved photoness

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#16]
I'd love to be able to:
1. Crop a photo I've just uploaded. (The Ravelry project page photo uploader and arranger is perfect, in my opinion.)
2. Rotate a photo I've just uploaded.
3. Indicate which person in a photo is me.

There's probably other stuff I've forgotten, but maybe others will post their suggestions too?

**Comment by fallax** [comment]
Possible other image upload improvements:

1) currently you can upload things that aren't an image, and you don't get an error.
2) currently you can upload the same image twice, and it doesn't tell you about it.

**Comment by SqaaSama** [comment]
I think it would be nice to be able to title/comment on your own pictures too.

**Comment by Cassolotl** [comment]
@SqaaSama This has been a thing for a while so you might have already noticed, but I feel I should say it here for completeness - titles and captions on photos are now possible. :)

You can also now crop and rotate photos.

**Comment by Cassolotl** [comment]
All of these are done now except one, which I have moved to #106.
