### ISSUE TITLE
Whitelist options: bulk whitelisting and switching off the whitelist

### ISSUE THREAD

**Issue by BarefootSelkie** [AndreaUnlimited/starfriends#17]
An option mass whitelist people would be nice, at the moment doing it manually takes a long time, so an option to add a lot of people to your whitelist at once would be useful.

**Comment by Cassolotl** [comment]
Yes! My preference is a setting that says something like "allow anyone to message me, even if I haven't whitelisted them" - and I think Andréa said she'd probably do that. She has lots of fine-tunable contact settings planned.

**Comment by fallerOfFalls** [comment]
is that what you meant @MxAithne? would being able to simply switch off the whitelist function so anyone could messsage you, solve this?

**Comment by fallax** [comment]
I think the whitelist being on by default is _really_ confusing - people expect that messages they send will get received, and there is no real explanation of how the whitelist works anywhere.

**Comment by fallerOfFalls** [comment]
agreed, whitelist being on by default without a bunch of those features being done, is very confusing.

**Comment by fallerOfFalls** [comment]
@MxAithne if this doesn't solve the problem/you meant something else, please say so!

**Comment by BarefootSelkie** [comment]
I meant something else, if you use the white list you need a way of possibly adding lots of people at once. e.g. tags seached and then being able to select all people and whitelist just them. So as well as being able to turn white list on and off being able to add people enmass.

**Comment by fallax** [comment]
Being able to say "I will whitelist all autistic people" or "I will whitelist all nonbinary people" so that you only get messages from those kind of people is I think what @MxAithne is looking for here? That'd be pretty useful - there's a similar feature on OKC which is really useful for only being seen/contacted by people who aren't straight, which is _really_ useful

**Comment by fallerOfFalls** [comment]
Ah yes! I get it now. Really good idea.

**Comment by fallax** [comment]
@AndreaUnlimited has now added a checkbox for switching off the whitelisting.

If you do use this to turn off whitelisting, the Whitelist page is then confusing, because it doesn't indicate that the whitelist is now deactivated, or how to turn it back on.

**Comment by Cassolotl** [comment]
This post is a mess. I'm closing it and starting a new post with the remaining issues/requests.
