### ISSUE TITLE
Warning that person hasn't white listed and won't recieve message

### ISSUE THREAD

**Issue by BarefootSelkie** [AndreaUnlimited/starfriends#18]
When you send a message to someone who hasn't white listed you it just seems like it's sent. There's currently no warning that they won't be able to see the message, so people might think they are being ignored.

**Comment by fallerOfFalls** [comment]
This is the same issue as #8 or at least related.

**Comment by BarefootSelkie** [comment]
Yep, but not quite the same, why I created seperate issues for them. As if someone wants to use the whitelist and not allow messages from everyone having a warning when you try and message that person would be useful. As some people find feeling ignored very distressing and it'd be helpful if they knew if they were being ignored or if the site was eating the messages.

**Comment by fallerOfFalls** [comment]
Yeah. I actually intended this as well with issue 8.

**Comment by fallerOfFalls** [comment]
@MxAithne I can see why you made a separate issue, but it's so relevant to issue 8 that I think it's better to just enhance issue 8 than to have separate issues for @AndreaUnlimited to deal with. They would (probably) be resolved together.
