### ISSUE TITLE
Random splashes like the ones when you log into Minecraft

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#20]
[Minecraft splashes](http://minecraft.gamepedia.com/index.php?title=Splash&redirect=no) are awesome and entertaining. Can we have something like that? (but maybe less stimmy).

Would change on every page reload

Splash Ideas already mentioned in Telegram group: 
CIS ALLOWED
It's OK to be CIS

Edit by Cassolotl: Resolved. Please see the [Tagline Suggestion Thread](https://github.com/AndreaUnlimited/starfriends/issues/23).

**Comment by Cassolotl** [comment]
I want this!

**Comment by AndreaUnlimited** [comment]
I need more ideas!

**Comment by Cassolotl** [comment]
Closing and redirecting you to the [Tagline Suggestion Thread](https://github.com/AndreaUnlimited/starfriends/issues/23). :)
