### ISSUE TITLE
Suggestion: Hide own profile from homepage

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#22]
I keep being my own best match! It feels weird to see my own profile on the homepage.

**Comment by AndreaUnlimited** [comment]
I like the idea of seeing myself, and seeing what other see when they see myself.
I could add it as a setting though? "Don't show myself"?

**Comment by Cassolotl** [comment]
Or a button on the "Edit Profile" page saying "view profile" maybe. But yeah, I see what you mean!

**Comment by Cassolotl** [comment]
Now there's a link to "My Profile", having me show up in searches is weird. But seeing match score with self is sometimes a source of amusement. So er, a setting letting you hide yourself in searches maybe?

**Comment by Cassolotl** [comment]
[There's a bounty on this](https://docs.google.com/spreadsheets/d/1qT56eFRbk5klbJ29k8Zf7eRhdTkw1awF4YGQM6cW-f8/edit?usp=sharing). Email me (Cassian) as per instructions in the bounty spreadsheet to add your bounty!

**Comment by Cassolotl** [comment]
Thing done. :)
