### ISSUE TITLE
Disallow leaving pronoun boxes empty when creating new pronouns

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#26]
The usual pronoun presentation is they/them/their/theirs/themself, but someone's entered "ze/zir///".

I'm not sure if this is a good idea, but again, it looks unpolished. And people need to provide all pronouns in the set so that the site knows how to talk about them!

**Comment by fallerOfFalls** [comment]
+1

**Comment by AndreaUnlimited** [comment]
yeah, though, it only works for english pronouns? I don't know what I should do about that.

**Comment by Cassolotl** [comment]
That's tricky. The "favourite" pronoun that gets shown under your photo on the homepage would presumably be the pronoun the site uses to talk about you, yes? So for the "favourite pronoun selector", you might only be able to choose from pronoun sets with all five English form boxes filled in.

Maybe at some point, if/when the site needs to be translated, you're/we're going to need some grammar-savvy multi-lingual folks to help design the pronoun form in different languages. So the first thing you do is select the language, and then the site shows you the form for entering pronouns in that language.

But if for now the best way to deal with this is to allow empty pronoun boxes, feel free to mark this issue "wontfix" and close it.

**Comment by AndreaUnlimited** [comment]
Alright, that sounds reasonable!
People can't leave fields empty anymore.
