### ISSUE TITLE
Users with no "Looking for" get no Top Matches

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#27]
Users who haven't set a "I am looking for..." get no matches under "Top Matches".

We probably need to a) show a list of matches and b) give people a link to their Edit Tags page with an instruction to fill more in to get better matches.

**Comment by AndreaUnlimited** [comment]
No everybody shows up when you have no match, and I added a little message telling the user to consider adding some tags, with a link to their Edit Tags page!

Thank you! \o/
