### ISSUE TITLE
Wanted: Example sentences for pronoun sets

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#28]
Someone's entered as a pronoun "they/them/their/theirs/themselves (singular verbs)", and it takes a little bit of mental gymnastics to work out that this means:

"They is going to their favourite ice cream shop, to treat themselves."

Some kind of hovertext example sentence for each pronoun set would be very helpful! At the moment you can only see example sentences when creating new pronoun sets, and it's not immediately clear that plural verbs does not equal plural person, for example.

**Comment by fallax** [comment]
I think there's a big problem with the distinction between (singular) and (plural) pronouns here - people are using (plural) when they should be using (singular).

(To avoid confusion, I believe (plural) is only normally appropriate for multiple systems here - if you are someone who is not multiple, you'd be wanting to use the (singular) version, I think?).

**Comment by Cassolotl** [comment]
Nope - singular they takes plural verbs, ie: they are. (Singular verbs would be "they is".) This is clear when entering new pronouns on the "create pronoun" thingy - checking and unchecking the box flips the example sentence between "is" and "are".

**Comment by fallax** [comment]
That explanation makes sense to me.

A related issue is that whichever option you choose (plural or singular), the pronoun choice appears exactly the same on their profile...

**Comment by Cassolotl** [comment]
> whichever option you choose (plural or singular), the pronoun choice appears exactly the same on their profile...

Ah yes! I thought of that, and then forgot. I'm glad someone else noticed! I think that needs to be a separate thing, so I'll make a new issue.

**Comment by Cassolotl** [comment]
[There's a bounty on this](https://docs.google.com/spreadsheets/d/1qT56eFRbk5klbJ29k8Zf7eRhdTkw1awF4YGQM6cW-f8/edit?usp=sharing). Email me (Cassian) as per instructions in the bounty spreadsheet to add your bounty!

**Comment by Cassolotl** [comment]
[There's a bounty on this](https://docs.google.com/spreadsheets/d/1qT56eFRbk5klbJ29k8Zf7eRhdTkw1awF4YGQM6cW-f8/edit?usp=sharing). Email me (Cassian) as per instructions in the bounty spreadsheet to add your bounty!

**Comment by AndreaUnlimited** [comment]
I think it's done?
It doesn't work on mobile but the mobile version is a different issue altogether?

**Comment by Cassolotl** [comment]
Yeah, I think this can be considered done. :)
