### ISSUE TITLE
Wanted: Make the pronoun box on "Edit Profile" vertically expandable

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#29]
So I scrolling isn't so fiddly on my computer/browser combo. I often like to embiggen little scrolly boxes to see more stuff at once.

**Comment by AndreaUnlimited** [comment]
What about a box using Chosen like that?
![2016-02-29_13h38_32](https://cloud.githubusercontent.com/assets/17512730/13394587/bb9da2d6-dee9-11e5-96df-09137ad8a736.png)

**Comment by Cassolotl** [comment]
Ohhhhh that's pleasing. :) I like it!

**Comment by AndreaUnlimited** [comment]
Alright, let's do this :)

**Comment by Cassolotl** [comment]
\o/

**Comment by Cassolotl** [comment]
The pronouns box is now much more user-friendly, and expands as you add more pronouns. :) Plus, it has a "you've saved your pronouns" pop-up!
