### ISSUE TITLE
Tag use counts are incorrect

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#3]
Counts of number of times that a tag has been used don't match up with the users listed on a search for that tag. Sometimes a tag is listed as being used but no users appear on the search; sometimes a tag lists "n" people using the tag when the search only displays "n-1" or "n-2" users.

For example, "men (3)" (tag 98) shows no results when searched for:

http://starfriends.org/index.php?search=tag&id=98

**Comment by AndreaUnlimited** [comment]
The number of time a tag is being used doesn't say where it was used, and you can't see what tags people are searching for, so it might say "3" even though nobody is actually identifying as this tag.

**Comment by Cassolotl** [comment]
This is partly why I suggested splitting the tags into "i am" and "looking for" lists - the tags in the "looking for" list could be plaintext.

**Comment by Cassolotl** [comment]
This could be labeled "invalid" or "wontfix" but I don't know which.
