### ISSUE TITLE
All tags page would be easier to read with columns

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#30]
Currently the All Tags page is just one big long vertical list.

By putting the list of tags in a <div> with this css applied:

```
-webkit-column-count: 3; /* Chrome, Safari, Opera */
-moz-column-count: 3; /* Firefox */
column-count: 3;
```

We could make the tags list fill the available space, which would make it easier to spot the one you want. I've attached what this would look like:

![columns](https://cloud.githubusercontent.com/assets/2036067/13373730/7f17cacc-dd67-11e5-9981-968019f457a5.png)

**Comment by AndreaUnlimited** [comment]
Done, thanks for the code!
