### ISSUE TITLE
Wanted: bump our own profile pics down a bit on the homepage

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#31]
Now that those buttons have been removed above the profile pics (woo!), my profile pic is a little raised:

![screen shot 2016-02-27 at 15 33 22](https://cloud.githubusercontent.com/assets/6607512/13373731/98918eb6-dd67-11e5-809c-b14ee88828e7.png)

**Comment by AndreaUnlimited** [comment]
Thank you!
It is fixed!
