### ISSUE TITLE
Suggestion: Statuses expire after x hours/days

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#33]
Possibly the amount of time could be changed in settings?

Just because my statuses often don't apply a few hours later.

**Comment by AndreaUnlimited** [comment]
I could also add the date when the status was written? Like if someone goes on vacations, they shouldn't have to (remember to) change the expiration date on their status?

**Comment by Cassolotl** [comment]
I like the "x [units of time] ago" wording, but yes, that would be cool too. :)

Maybe auto-expire could be an opt-in setting? I'd prefer that.

**Comment by AndreaUnlimited** [comment]
Alright, I think I will do both.

**Comment by Cassolotl** [comment]
[There's a bounty on this](https://docs.google.com/spreadsheets/d/1qT56eFRbk5klbJ29k8Zf7eRhdTkw1awF4YGQM6cW-f8/edit?usp=sharing). Email me (Cassian) as per instructions in the bounty spreadsheet to add your bounty!

**Comment by Cassolotl** [comment]
The Feed has replaced this function and the status may or may not be repurposed, but it won't need an auto-expiry feature. So this can be closed. :)
