### ISSUE TITLE
Pages get unneeded horizontal scrollbar

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#35]
This can be removed by adding margin: 0; to the CSS for the BODY element.

![scrollbar](https://cloud.githubusercontent.com/assets/2036067/13373964/8568e85a-dd6e-11e5-8a73-776a74522e66.png)

**Comment by AndreaUnlimited** [comment]
Done! Thank for telling me what to do, that's so much easier XD
