### ISSUE TITLE
Edit profile: entering a non-number age fails weirdly

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#37]
If you enter an age that isn't a number, rather than getting an error, or remaining blank, it gets set to 0.

**Comment by Cassolotl** [comment]
No longer relevant, as age is entered with a fancy DoB form now:

![screen shot 2016-09-05 at 17 04 41](https://cloud.githubusercontent.com/assets/6607512/18253221/de28cc0a-738a-11e6-9fa5-9b80562da4e8.png)
