### ISSUE TITLE
Removing all tags from "I am looking for" puts tags from "I am" into the box instead

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#39]
Instructions to reproduce:

1) Make sure you've got some tags in "I am" 
2) Remove all tags from "I am looking for..."
3) Press "Save Changes".
4) Some tags from "I am" will appear in "I am looking for" as well.

**Comment by Cassolotl** [comment]
This happened to me; latest version of Chrome on Mac OS X 10.11.3 if that's relevant.

**Comment by Cassolotl** [comment]
I just tested for this bug (in Safari on a Mac) and it appears to be gone? So that's nice! If it isn't gone leave a comment and I'll look into it.
