### ISSUE TITLE
No helpful error on incorrect username/password

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#4]
If someone enters the wrong username or password, they are redirected to a completely blank page, rather than an indication that something has gone wrong or what they can do.

You can reproduce this by putting in any incorrect username or password on the login page (e.g. "hat" + "badger")

**Comment by Cassolotl** [comment]
Awwwwww yes

![screen shot 2016-09-03 at 21 08 20](https://cloud.githubusercontent.com/assets/6607512/18227395/93af8e1e-721a-11e6-810f-fc14801a30b2.png)
