### ISSUE TITLE
Buttons on pages don't show a confirmation message to show the change was accepted

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#40]
Normally users expect to see a "Success" message when a button is pressed to submit something.

Currently when you save changes on "Edit Settings", "Edit Tags", or "Edit Profile", nothing new appears to say the data was saved, meaning you have to go and check whether your changes saved okay or not.

**Comment by Cassolotl** [comment]
[There's a bounty on this](https://docs.google.com/spreadsheets/d/1qT56eFRbk5klbJ29k8Zf7eRhdTkw1awF4YGQM6cW-f8/edit?usp=sharing). Email me (Cassian) as per instructions in the bounty spreadsheet to add your bounty!

**Comment by Cassolotl** [comment]
There are now saving confirmation pop-ups on Edit Profile, but not Edit Settings or Edit Tags yet.

**Comment by AndreaUnlimited** [comment]
There are now saving confirmation pop-ups for Edit Settings and Edit Tags, but I'm still working on the rest.
It would help greatly if you could just write the name of the page in the comments everytime you encounter that kind of problem, so that I can make a proper list!

**Comment by Cassolotl** [comment]
Okay, here's pages where there are changes that can be saved, and whether or not there's a confirmation message that it's been saved:
- **No confirmation.** https://www.starfriends.org/edit/gallery - Set as profile picture. It works, but there's no pop-up.
- **No confirmation.** https://www.starfriends.org/index.php?edit=gallery&set=rights&img=IMAGENUMBER - In the filters thing at the top right corner, clicking save closes the pop-out settings, but there is no confirmation message.
- **Unknown.** https://www.starfriends.org/edit/pronouns Create a new set of pronouns - _unknown - I don't have a new set to create_
- **Functional but weird.** https://www.starfriends.org/edit/gallery Add an image to my gallery - a pop-up appears with a big green tick on it, but disappears too quickly to read. Uploaded image appears in gallery.

All fine:
- https://www.starfriends.org/edit/profile - Success! Profile saved.
- https://www.starfriends.org/edit/pronouns Select pronoun(s) - Success! Your pronouns have been saved properly.
- https://www.starfriends.org/edit/pronouns Advanced pronoun settings - Success! Your settings have been saved properly.
- https://www.starfriends.org/index.php?edit=gallery&set=rights&img=NUMBER - Success! Your image's settings have been updated.
- https://www.starfriends.org/edit/tags - Success! Your tags have been properly saved!
- https://www.starfriends.org/edit/settings - Success! Your settings have been properly updated!

I can't find any more places where you edit things and then save.

Hopefully this helps!

**Comment by AndreaUnlimited** [comment]
All the above done and checked.

For pages where there are the little filter icon in the top right corner, the Matches and the Feed pages don't actually show confirmation, but automatically updates the content of the page, so I think it's enough to tell the user the settings have been saved?

I might be wrong though!

**Comment by Cassolotl** [comment]
Awesome! :)

> For pages where there are the little filter icon in the top right corner, the Matches and the Feed pages don't actually show confirmation, but automatically updates the content of the page, so I think it's enough to tell the user the settings have been saved?
> 
> I might be wrong though!

Nah, I think that's okay. :)
