### ISSUE TITLE
Make a better mobile version of the website

### ISSUE THREAD

**Issue by quarridors** [AndreaUnlimited/starfriends#42]
The site is unnecessarily difficult to use on mobile devices due to having a 960px fixed width content container and no viewport defined.

By adding this tag to the header:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

And setting all `width:960px` or `width:920px` attributes to `width:100%` or `width:90%`, I was able to make the site much more comfortable for use on tablets or phones. See attachments.

<img width="642" alt="screen shot 2016-02-28 at 15 54 50" src="https://cloud.githubusercontent.com/assets/17530237/13380199/5e6a1bda-de35-11e5-850c-afaa0186bc24.png">
<img width="398" alt="screen shot 2016-02-28 at 15 56 56" src="https://cloud.githubusercontent.com/assets/17530237/13380201/6166c5ae-de35-11e5-9b2e-4517b71ac163.png">

(You will probably also need to set the matched div elements to centre when they're not full width, or make them fill the available space using flexboxes. But as an alpha site I don't think that's necessary at this stage, making it fit on phone screens is higher priority.)

**Comment by AndreaUnlimited** [comment]
Some responsiveness has been added - by Emrys

**Comment by quarridors** [comment]
Brilliant, thank you!

There's some strange horizontal scrolling going on when I view on my mobile but it's much more useable now.

This is scrolled to the side as far as it goes:
![2016-02-28 16 36 51](https://cloud.githubusercontent.com/assets/17530237/13380384/92a5e934-de39-11e5-9274-1ac65c017f4d.png)

**Comment by fallax** [comment]
The strange horizontal scrolling is caused by the relative positioning ".match-buttons" DIV tag that contains the whitelist/blacklist/message icons. On desktop browsers, it causes a horizontal scrollbar to appear at small window sizes.

We can fix this by setting a width on .matchbuttons:

```
.match-buttons { width: 75px }
```

**Comment by AndreaUnlimited** [comment]
it doesn't seem to solve the problem :(

**Comment by AndreaUnlimited** [comment]
I hid the overflow until I can find a better way. Should be fine on mobile!

**Comment by quarridors** [comment]
Side scrolling on mobile fixed now, thank you!

**Comment by fallax** [comment]
There are still some fixed widths on people's profile detail pages (the ones you get to if you click on someone's name) - #profilepage and #profilepage-summary have fixed widths that stop the page reflowing nicely at smaller screen sizes. @quarridors I don't have a decent phone here - do profile pages look okay as they are or would that page benefit from fixing that?

**Comment by fallax** [comment]
@AndreaUnlimited provided this screenshot, clearly that is a problem.

![421214411_53911_16462034334592898769](https://cloud.githubusercontent.com/assets/2036067/13381019/85715582-de48-11e5-8c4f-17031b2be2ce.jpg)

There is similar stuff on the Whitelist page, so that probably needs fixing too.

**Comment by quarridors** [comment]
@fallax Profile pages aren't very usable on mobile, no, they're effectively fixed width. The text content should wrap under the picture after a certain size, I think, then scale with width,

**Comment by Cassolotl** [comment]
These issues are now resolved. If people have issues in mobile browsers they should report the problems in new issues, which can be resolved here individually as Andréa fixes them.
