### ISSUE TITLE
Make it possible to change your email address

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#45]
in "settings" maybe?

**Comment by AndreaUnlimited** [comment]
It is already possible, and it _is_ in "settings".

**Comment by fallerOfFalls** [comment]
oh, it's not surrounded by a box, so it's not clear that you can change it.

**Comment by AndreaUnlimited** [comment]
Alright, I added a border.

**Comment by fallerOfFalls** [comment]
oh yeah that's better. could the number for "Only show x profiles per page"  have a border as well?

and maybe it could be like:
Only show [`6`] profiles per page

?

**Comment by AndreaUnlimited** [comment]
oh, I like, and DONE!

Don't hesitate to reopen issue if you're not done, by the way!

**Comment by fallerOfFalls** [comment]
weee awesome!
