### ISSUE TITLE
Suggestion: 'report abuse' button

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#50]
At some point we're going to need a mechanism for reporting users who are causing trouble to the site admins.

Putting this here so it doesn't get forgotten about.

**Comment by AndreaUnlimited** [comment]
Thank you!

The idea is to be able to block people, and report people, pictures and messages.

Did I forgot anything?

**Comment by Cassolotl** [comment]
A report system is now in place! Profiles, feed posts, tag comments can all be reported.
