### ISSUE TITLE
"You" field tags don't have pop-ups

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#55]
Link to first tweet: https://twitter.com/actuallyitsmx/status/705022735081205760

> Are you finding that the tags work fine in the "I am/have/do" field but not the "you are/have/do" field, or is that just me?
> 
> I put in the words of the tags but the tags don't pop up for selection like they do in the "me" field.

**Comment by AndreaUnlimited** [comment]
Fixed!
