### ISSUE TITLE
Left side navigation obscures page on small screens

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#6]
On small screens (e.g. phones/tablets) and small window sizes, the left hand side navigation links hide part of the page. This means that many pages become really difficult to use.

![starfriendsbug](https://cloud.githubusercontent.com/assets/2036067/13372747/5c882128-dd49-11e5-9f31-fc370d1457e7.png)

**Comment by fallax** [comment]
Suggestion: we could probably fix this by doing the following:
- take the fixed widths off of page elements like the "hello" and "header" divs
- take the width and the margin:auto padding off of the "content" div, and put some left padding on it instead (e.g. margin-left: 220px;) to make room for the left navigation
- put the following on the BODY element to centre the page again
  margin-left: auto;
  margin-right: auto;
  max-width: 1280px;

Not tested this extensively but would probably be a good first step towards fixing this

**Comment by AndreaUnlimited** [comment]
I put the menu on top of the page.
