### ISSUE TITLE
Wanted: Sent messages

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#62]
If I message someone new, I don't see the message I sent to them until they reply (or maybe just until they read it?).

It would be cool to see sent messages somewhere, somehow. It feels most intuitive to me to have them listed with conversations and received messages, but I don't really mind.

**Comment by AndreaUnlimited** [comment]
Messages sent can now be seen in the inbox. Messages to and from a single person are now packed under a unique discussion id.
