### ISSUE TITLE
Some kind of visual indicator on profiles of people who're mutually whitelisty

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#69]
This is a bad title. I apologise. :D 

Anyway, some kind of indicator on someone's profile if you've whitelisted each other, which could also be visible on the whitelist page itself maybe? I think that could be cool.

**Comment by fallerOfFalls** [comment]
I think this is part of #8. There are no indicators anywhere yet. if you agree, please close this issue (so there are less issues and it's easier for @AndreaUnlimited to see what needs attention).

**Comment by Cassolotl** [comment]
Yes, I think you're probably right. :)
