### ISSUE TITLE
email notifications don't happen

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#70]
I have the "Send me an e-mail when I get a new message" box ticked. Someone sent me a message on starfriends, but I didn't get an email. I've never had an email. Has anyone else received an email from starfriends?

**Comment by AndreaUnlimited** [comment]
E-mails are probably in your spam folder, can you check that?

**Comment by fallerOfFalls** [comment]
The emails were not and are not in my spam folder.

**Comment by fallerOfFalls** [comment]
Although feel free to test it again by sending me a message on starfriends

**Comment by SqaaSama** [comment]
Might be a problem unique to you because so far I have received emails consistently with messages, with the exception of notifications of being added to someone's whitelist.
