### ISSUE TITLE
filter inactive users

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#71]
could just be a setting: "only display users who have logged in in the last x months"? Just so we don't spend all our time looking at innactive users who will probably never read our messages.

Or it could be implemented as a non tag filter, beside "You'd be/do/have": logged in in the last `2` months.

**Comment by fallerOfFalls** [comment]
more thoughts from discussion on Telegram:

instead of "show uses who have logged in in the last x days/weeks/months", just a "hide inactive users" checkbox (either in settings or by the You'd be/do/have tags) - default checked. And a non-customisable (but prominently advertised) amount of time after which a user is considered inactive, e.g. a month (or longer? 2 months? 6?). If a user doesn't log in for that amount of time, they are sent an email to warn them that they are considered an inactive user, and will not be displayed to most users until they log in again.

Oh hey instead of being a fixed amount of time, it the time after which they are considered inactive, could increase the longer they've been active for. So if you log in just once, then you're considered inactive after a week (?) and if you've logged in a week after you signed up, then you're considered active for a month without logging in etc. Or some neat algorithm? The point being, there'll be users who log in once, look around, and then lose interest, and are inactive thereafter. And there'll be users who have done all their own searching and therefore aren't logging in, but are still interested in receiving messages, but don't necessarily want to have to log in frequently just to be considered active.

**Comment by fallerOfFalls** [comment]
also "hide in active users" being optional may be unnecessary, and complicates the "you're considered inactive" message. so maybe it doesn't even need to be an option.

**Comment by Cassolotl** [comment]
[There's a bounty on this](https://docs.google.com/spreadsheets/d/1qT56eFRbk5klbJ29k8Zf7eRhdTkw1awF4YGQM6cW-f8/edit?usp=sharing). Email me (Cassian) as per instructions in the bounty spreadsheet to add your bounty!

**Comment by Cassolotl** [comment]
@fallerOfFalls Do you consider this completed with the new filter on the Matches page?

![screen shot 2016-07-22 at 21 45 50](https://cloud.githubusercontent.com/assets/6607512/17070758/b0558942-5055-11e6-9803-47d7bb4124fa.png)

Edit: Reading your comments more closely, what we have is clearly not what you were going for. :D Sorry!

**Comment by fallerOfFalls** [comment]
@Cassolotl yeah, uh, no.

an additional florish: when you look at an "inactive user" profile there could be an indication "this user is considered innactive by our algorithm".

**Comment by Cassolotl** [comment]
> an additional florish: when you look at an "inactive user" profile there could be an indication "this user is considered innactive by our algorithm".

Hmmm, not sure I like that so much? :/

**Comment by Cassolotl** [comment]
It's in the works!

> Andréa, [11.02.17 13:15]
> I hope to be able to get enough data to do that next week-end

**Comment by Cassolotl** [comment]
Done. :)
