### ISSUE TITLE
Sign up page doesn't validate any fields you enter

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#75]
Currently when you're signing up none of the fields get validated.

1) If someone puts something in the "email" box, we need to check it looks vaguely like an email (and they've not just got confused)
2) If someone puts something in the "display name" box, we should make sure it's something that would actually fit on the screen (e.g. not 50+ characters)
3) If someone enters a password, we should make sure it is usefully strong (e.g. more than 6 characters) and not unusable (more than 64 characters)

**Comment by fallax** [comment]
Something like http://jqueryvalidation.org/ might be useful for implementing this.

**Comment by Cassolotl** [comment]
This seems to be done! :)
