### ISSUE TITLE
Improved paging controls in Top Matches

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#77]
The paging controls on Top Matches are heading towards getting a bit ridiculous:

![paging](https://cloud.githubusercontent.com/assets/2036067/13902166/53edb4cc-ee35-11e5-9614-1f443d180c1e.png)

If we get many more users, this will start wrapping around multiple lines, even on a desktop browser.

Something a bit more like Google's paging controls would work better - a "previous" link, a "next" link, and the ten nearest pages to the current page.

![googlepaging](https://cloud.githubusercontent.com/assets/2036067/13902167/8c06013e-ee35-11e5-85d4-999b9705dab1.png)

**Comment by Cassolotl** [comment]
I once went to a site where those controls at the bottom of the page were like google's, plus there was a little box where you could type a page number and press enter and it'd take you to any page. I think that could be cool, for jumping to middle pages without having to go through lots of numbers in between.
