### ISSUE TITLE
Indicate who has whitelisted you whereever relevant

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#8]
e.g. notify you when someone whitelists you.

**Comment by fallerOfFalls** [comment]
oh, and it shouldn't just be a one-off notification. there should be an accessible list of users who have whitelisted you.

**Comment by fallerOfFalls** [comment]
Whether they have whitelisted you should also be clearly indicated when attempting to message you, as elaborated on in #18. and should indicate on the home page, and should be a filter option etc.

**Comment by Cassolotl** [comment]
From #69 - "some kind of indicator on someone's profile if you've whitelisted each other, which could also be visible on the whitelist page itself maybe? I think that could be cool."

**Comment by Cassolotl** [comment]
I'm here tidying up the Github space, and I thought I'd update us on this issue.

When you and another person have whitelisted each other there is an indicator over their photo on the Matches tab and on their profile like this (top left):

![screen shot 2017-02-11 at 17 41 36](https://cloud.githubusercontent.com/assets/6607512/22856011/606ab4f8-f081-11e6-8f47-9b9c28d0b06b.png)

You also get whitelist notifications in your Feed, if you have that setting checked in your Feed filters:

![screen shot 2017-02-11 at 17 42 11](https://cloud.githubusercontent.com/assets/6607512/22856015/7f1244ac-f081-11e6-85c5-0d66ef2ab7a3.png)

**Comment by Cassolotl** [comment]
Things that are still wanted appear to be:

- a list of people who have whitelisted you
- ability to filter matches by whether they have whitelisted you
- indication when you're messaging someone whether they have whitelisted you

Right?

**Comment by Cassolotl** [comment]
A bunch of this is included in the Beta plan, so I'll just... readd that... \*cough\*

**Comment by Cassolotl** [comment]
Done!
