### ISSUE TITLE
Wanted: ability to paragraphs in profile

### ISSUE THREAD

**Issue by Cassolotl** [AndreaUnlimited/starfriends#80]
Not sure whether this is a bug or a new feature request, but I'm posting it for Freyr because they're at my house.

Long text paragraphs in the profile editing thing (Summary, Likes, Dislikes) remove carriage returns.

**Comment by AndreaUnlimited** [comment]
Done.

**Comment by Cassolotl** [comment]
Ahhhh! :D <3 Thanks!
